// Generated by Dagger (https://google.github.io/dagger).
package com.githubuiviewer.old.datasource.api;

import android.content.Context;
import dagger.internal.Factory;
import javax.inject.Provider;

public final class ErrorInterceptor_Factory implements Factory<ErrorInterceptor> {
  private final Provider<Context> contextProvider;

  public ErrorInterceptor_Factory(Provider<Context> contextProvider) {
    this.contextProvider = contextProvider;
  }

  @Override
  public ErrorInterceptor get() {
    return provideInstance(contextProvider);
  }

  public static ErrorInterceptor provideInstance(Provider<Context> contextProvider) {
    return new ErrorInterceptor(contextProvider.get());
  }

  public static ErrorInterceptor_Factory create(Provider<Context> contextProvider) {
    return new ErrorInterceptor_Factory(contextProvider);
  }

  public static ErrorInterceptor newErrorInterceptor(Context context) {
    return new ErrorInterceptor(context);
  }
}
