// Generated by Dagger (https://google.github.io/dagger).
package com.githubuiviewer.old.datasource.api;

import com.githubuiviewer.old.tools.sharedPrefsTools.SharedPref;
import dagger.internal.Factory;
import javax.inject.Provider;

public final class HeaderInterceptor_Factory implements Factory<HeaderInterceptor> {
  private final Provider<SharedPref> sharedPrefProvider;

  public HeaderInterceptor_Factory(Provider<SharedPref> sharedPrefProvider) {
    this.sharedPrefProvider = sharedPrefProvider;
  }

  @Override
  public HeaderInterceptor get() {
    return provideInstance(sharedPrefProvider);
  }

  public static HeaderInterceptor provideInstance(Provider<SharedPref> sharedPrefProvider) {
    return new HeaderInterceptor(sharedPrefProvider.get());
  }

  public static HeaderInterceptor_Factory create(Provider<SharedPref> sharedPrefProvider) {
    return new HeaderInterceptor_Factory(sharedPrefProvider);
  }

  public static HeaderInterceptor newHeaderInterceptor(SharedPref sharedPref) {
    return new HeaderInterceptor(sharedPref);
  }
}
