// Generated by Dagger (https://google.github.io/dagger).
package com.githubuiviewer.old.ui.issueScreen;

import com.githubuiviewer.old.data.repository.GitHubRepository;
import com.githubuiviewer.newpackage.GitHubService;
import dagger.internal.Factory;
import javax.inject.Provider;

public final class IssueViewModel_Factory implements Factory<IssueViewModel> {
  private final Provider<GitHubService> gitHubServiceProvider;

  private final Provider<GitHubRepository> gitHubRepositoryProvider;

  public IssueViewModel_Factory(
      Provider<GitHubService> gitHubServiceProvider,
      Provider<GitHubRepository> gitHubRepositoryProvider) {
    this.gitHubServiceProvider = gitHubServiceProvider;
    this.gitHubRepositoryProvider = gitHubRepositoryProvider;
  }

  @Override
  public IssueViewModel get() {
    return provideInstance(gitHubServiceProvider, gitHubRepositoryProvider);
  }

  public static IssueViewModel provideInstance(
      Provider<GitHubService> gitHubServiceProvider,
      Provider<GitHubRepository> gitHubRepositoryProvider) {
    return new IssueViewModel(gitHubServiceProvider.get(), gitHubRepositoryProvider.get());
  }

  public static IssueViewModel_Factory create(
      Provider<GitHubService> gitHubServiceProvider,
      Provider<GitHubRepository> gitHubRepositoryProvider) {
    return new IssueViewModel_Factory(gitHubServiceProvider, gitHubRepositoryProvider);
  }

  public static IssueViewModel newIssueViewModel(
      GitHubService gitHubService, GitHubRepository gitHubRepository) {
    return new IssueViewModel(gitHubService, gitHubRepository);
  }
}
