// Generated by Dagger (https://google.github.io/dagger).
package com.githubuiviewer.old.ui.issueScreen;

import dagger.MembersInjector;
import javax.inject.Provider;

public final class IssueFragment_MembersInjector implements MembersInjector<IssueFragment> {
  private final Provider<IssueViewModel> viewModelProvider;

  public IssueFragment_MembersInjector(Provider<IssueViewModel> viewModelProvider) {
    this.viewModelProvider = viewModelProvider;
  }

  public static MembersInjector<IssueFragment> create(Provider<IssueViewModel> viewModelProvider) {
    return new IssueFragment_MembersInjector(viewModelProvider);
  }

  @Override
  public void injectMembers(IssueFragment instance) {
    injectViewModel(instance, viewModelProvider.get());
  }

  public static void injectViewModel(IssueFragment instance, IssueViewModel viewModel) {
    instance.viewModel = viewModel;
  }
}
