// Generated by Dagger (https://google.github.io/dagger).
package com.githubuiviewer.old.tools.sharedPrefsTools;

import android.content.Context;
import dagger.internal.Factory;
import javax.inject.Provider;

public final class SharedPref_Factory implements Factory<SharedPref> {
  private final Provider<Context> contextProvider;

  public SharedPref_Factory(Provider<Context> contextProvider) {
    this.contextProvider = contextProvider;
  }

  @Override
  public SharedPref get() {
    return provideInstance(contextProvider);
  }

  public static SharedPref provideInstance(Provider<Context> contextProvider) {
    return new SharedPref(contextProvider.get());
  }

  public static SharedPref_Factory create(Provider<Context> contextProvider) {
    return new SharedPref_Factory(contextProvider);
  }

  public static SharedPref newSharedPref(Context context) {
    return new SharedPref(context);
  }
}
