// Generated by Dagger (https://google.github.io/dagger).
package com.githubuiviewer.old.di;

import android.content.Context;
import com.githubuiviewer.old.tools.sharedPrefsTools.SharedPref;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import javax.inject.Provider;
import retrofit2.Retrofit;
import retrofit2.converter.gson.GsonConverterFactory;

public final class AppModule_ProvideRetrofitFactory implements Factory<Retrofit> {
  private final AppModule module;

  private final Provider<GsonConverterFactory> gsonConverterFactoryProvider;

  private final Provider<SharedPref> sharedPrefProvider;

  private final Provider<Context> contextProvider;

  public AppModule_ProvideRetrofitFactory(
      AppModule module,
      Provider<GsonConverterFactory> gsonConverterFactoryProvider,
      Provider<SharedPref> sharedPrefProvider,
      Provider<Context> contextProvider) {
    this.module = module;
    this.gsonConverterFactoryProvider = gsonConverterFactoryProvider;
    this.sharedPrefProvider = sharedPrefProvider;
    this.contextProvider = contextProvider;
  }

  @Override
  public Retrofit get() {
    return provideInstance(
        module, gsonConverterFactoryProvider, sharedPrefProvider, contextProvider);
  }

  public static Retrofit provideInstance(
      AppModule module,
      Provider<GsonConverterFactory> gsonConverterFactoryProvider,
      Provider<SharedPref> sharedPrefProvider,
      Provider<Context> contextProvider) {
    return proxyProvideRetrofit(
        module,
        gsonConverterFactoryProvider.get(),
        sharedPrefProvider.get(),
        contextProvider.get());
  }

  public static AppModule_ProvideRetrofitFactory create(
      AppModule module,
      Provider<GsonConverterFactory> gsonConverterFactoryProvider,
      Provider<SharedPref> sharedPrefProvider,
      Provider<Context> contextProvider) {
    return new AppModule_ProvideRetrofitFactory(
        module, gsonConverterFactoryProvider, sharedPrefProvider, contextProvider);
  }

  public static Retrofit proxyProvideRetrofit(
      AppModule instance,
      GsonConverterFactory gsonConverterFactory,
      SharedPref sharedPref,
      Context context) {
    return Preconditions.checkNotNull(
        instance.provideRetrofit(gsonConverterFactory, sharedPref, context),
        "Cannot return null from a non-@Nullable @Provides method");
  }
}
