// Generated by Dagger (https://google.github.io/dagger).
package com.githubuiviewer.old.di;

import com.githubuiviewer.newpackage.GitHubService;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import javax.inject.Provider;
import retrofit2.Retrofit;

public final class AppModule_ProvideGitHubReposApiFactory implements Factory<GitHubService> {
  private final AppModule module;

  private final Provider<Retrofit> retrofitProvider;

  public AppModule_ProvideGitHubReposApiFactory(
      AppModule module, Provider<Retrofit> retrofitProvider) {
    this.module = module;
    this.retrofitProvider = retrofitProvider;
  }

  @Override
  public GitHubService get() {
    return provideInstance(module, retrofitProvider);
  }

  public static GitHubService provideInstance(
      AppModule module, Provider<Retrofit> retrofitProvider) {
    return proxyProvideGitHubReposApi(module, retrofitProvider.get());
  }

  public static AppModule_ProvideGitHubReposApiFactory create(
      AppModule module, Provider<Retrofit> retrofitProvider) {
    return new AppModule_ProvideGitHubReposApiFactory(module, retrofitProvider);
  }

  public static GitHubService proxyProvideGitHubReposApi(AppModule instance, Retrofit retrofit) {
    return Preconditions.checkNotNull(
        instance.provideGitHubReposApi(retrofit),
        "Cannot return null from a non-@Nullable @Provides method");
  }
}
