// Generated by Dagger (https://google.github.io/dagger).
package com.githubuiviewer.old.di;

import android.content.Context;
import dagger.internal.Factory;
import dagger.internal.Preconditions;

public final class AppModule_ContextFactory implements Factory<Context> {
  private final AppModule module;

  public AppModule_ContextFactory(AppModule module) {
    this.module = module;
  }

  @Override
  public Context get() {
    return provideInstance(module);
  }

  public static Context provideInstance(AppModule module) {
    return proxyContext(module);
  }

  public static AppModule_ContextFactory create(AppModule module) {
    return new AppModule_ContextFactory(module);
  }

  public static Context proxyContext(AppModule instance) {
    return Preconditions.checkNotNull(
        instance.context(), "Cannot return null from a non-@Nullable @Provides method");
  }
}
