// Generated by Dagger (https://google.github.io/dagger).
package com.githubuiviewer.old.di;

import android.content.Context;
import com.githubuiviewer.old.tools.sharedPrefsTools.SharedPref;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import javax.inject.Provider;

public final class AppModule_ProvideSharedPrefFactory implements Factory<SharedPref> {
  private final AppModule module;

  private final Provider<Context> contextProvider;

  public AppModule_ProvideSharedPrefFactory(AppModule module, Provider<Context> contextProvider) {
    this.module = module;
    this.contextProvider = contextProvider;
  }

  @Override
  public SharedPref get() {
    return provideInstance(module, contextProvider);
  }

  public static SharedPref provideInstance(AppModule module, Provider<Context> contextProvider) {
    return proxyProvideSharedPref(module, contextProvider.get());
  }

  public static AppModule_ProvideSharedPrefFactory create(
      AppModule module, Provider<Context> contextProvider) {
    return new AppModule_ProvideSharedPrefFactory(module, contextProvider);
  }

  public static SharedPref proxyProvideSharedPref(AppModule instance, Context context) {
    return Preconditions.checkNotNull(
        instance.provideSharedPref(context),
        "Cannot return null from a non-@Nullable @Provides method");
  }
}
