// Generated by Dagger (https://google.github.io/dagger).
package com.githubuiviewer.old.di;

import dagger.internal.Factory;
import dagger.internal.Preconditions;
import retrofit2.converter.gson.GsonConverterFactory;

public final class AppModule_ProvideGsonConverterFactoryFactory
    implements Factory<GsonConverterFactory> {
  private final AppModule module;

  public AppModule_ProvideGsonConverterFactoryFactory(AppModule module) {
    this.module = module;
  }

  @Override
  public GsonConverterFactory get() {
    return provideInstance(module);
  }

  public static GsonConverterFactory provideInstance(AppModule module) {
    return proxyProvideGsonConverterFactory(module);
  }

  public static AppModule_ProvideGsonConverterFactoryFactory create(AppModule module) {
    return new AppModule_ProvideGsonConverterFactoryFactory(module);
  }

  public static GsonConverterFactory proxyProvideGsonConverterFactory(AppModule instance) {
    return Preconditions.checkNotNull(
        instance.provideGsonConverterFactory(),
        "Cannot return null from a non-@Nullable @Provides method");
  }
}
