// Generated by Dagger (https://google.github.io/dagger).
package com.githubuiviewer.old.di;

import com.githubuiviewer.old.data.repository.GitHubRepository;
import com.githubuiviewer.newpackage.GitHubService;
import com.githubuiviewer.old.tools.sharedPrefsTools.SharedPref;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import javax.inject.Provider;

public final class AppModule_ProvideProfileRepositoryFactory implements Factory<GitHubRepository> {
  private final AppModule module;

  private final Provider<GitHubService> gitHubServiceProvider;

  private final Provider<SharedPref> sharedPrefProvider;

  public AppModule_ProvideProfileRepositoryFactory(
      AppModule module,
      Provider<GitHubService> gitHubServiceProvider,
      Provider<SharedPref> sharedPrefProvider) {
    this.module = module;
    this.gitHubServiceProvider = gitHubServiceProvider;
    this.sharedPrefProvider = sharedPrefProvider;
  }

  @Override
  public GitHubRepository get() {
    return provideInstance(module, gitHubServiceProvider, sharedPrefProvider);
  }

  public static GitHubRepository provideInstance(
      AppModule module,
      Provider<GitHubService> gitHubServiceProvider,
      Provider<SharedPref> sharedPrefProvider) {
    return proxyProvideProfileRepository(
        module, gitHubServiceProvider.get(), sharedPrefProvider.get());
  }

  public static AppModule_ProvideProfileRepositoryFactory create(
      AppModule module,
      Provider<GitHubService> gitHubServiceProvider,
      Provider<SharedPref> sharedPrefProvider) {
    return new AppModule_ProvideProfileRepositoryFactory(
        module, gitHubServiceProvider, sharedPrefProvider);
  }

  public static GitHubRepository proxyProvideProfileRepository(
      AppModule instance, GitHubService gitHubService, SharedPref sharedPref) {
    return Preconditions.checkNotNull(
        instance.provideProfileRepository(gitHubService, sharedPref),
        "Cannot return null from a non-@Nullable @Provides method");
  }
}
