// Generated by Dagger (https://google.github.io/dagger).
package com.githubuiviewer.old.di;

import com.githubuiviewer.old.ui.BaseViewModel;
import dagger.internal.Factory;
import dagger.internal.Preconditions;

public final class AppModule_ProvideBaseViewModelFactory implements Factory<BaseViewModel> {
  private final AppModule module;

  public AppModule_ProvideBaseViewModelFactory(AppModule module) {
    this.module = module;
  }

  @Override
  public BaseViewModel get() {
    return provideInstance(module);
  }

  public static BaseViewModel provideInstance(AppModule module) {
    return proxyProvideBaseViewModel(module);
  }

  public static AppModule_ProvideBaseViewModelFactory create(AppModule module) {
    return new AppModule_ProvideBaseViewModelFactory(module);
  }

  public static BaseViewModel proxyProvideBaseViewModel(AppModule instance) {
    return Preconditions.checkNotNull(
        instance.provideBaseViewModel(),
        "Cannot return null from a non-@Nullable @Provides method");
  }
}
