// Generated by Dagger (https://google.github.io/dagger).
package com.githubuiviewer.old.di;

import android.content.Context;
import com.githubuiviewer.old.data.repository.GitHubRepository;
import com.githubuiviewer.newpackage.GitHubService;
import com.githubuiviewer.old.tools.sharedPrefsTools.SharedPref;
import com.githubuiviewer.old.ui.issueScreen.IssueFragment;
import com.githubuiviewer.old.ui.issueScreen.IssueFragment_MembersInjector;
import com.githubuiviewer.old.ui.issueScreen.IssueViewModel;
import com.githubuiviewer.old.ui.navigator.BaseFragment;
import com.githubuiviewer.old.ui.projectScreen.contributors.ContributorsFragment;
import com.githubuiviewer.old.ui.projectScreen.contributors.ContributorsFragment_MembersInjector;
import com.githubuiviewer.old.ui.projectScreen.contributors.ContributorsViewModel;
import com.githubuiviewer.old.ui.projectScreen.issues.BriefInfoIssuesFragment;
import com.githubuiviewer.old.ui.projectScreen.issues.BriefInfoIssuesFragment_MembersInjector;
import com.githubuiviewer.old.ui.projectScreen.issues.IssuesBriefInfoViewModel;
import com.githubuiviewer.old.ui.projectScreen.readme.ReadMeFragment;
import com.githubuiviewer.old.ui.projectScreen.readme.ReadMeFragment_MembersInjector;
import com.githubuiviewer.old.ui.projectScreen.readme.ReadMeViewModel;
import com.githubuiviewer.old.ui.updateTokenFragment.UpdateTokenFragment;
import com.githubuiviewer.old.ui.updateTokenFragment.UpdateTokenFragment_MembersInjector;
import com.githubuiviewer.old.ui.updateTokenFragment.UpdateTokenViewModel;
import com.githubuiviewer.old.ui.userScreen.UserFragment;
import com.githubuiviewer.old.ui.userScreen.UserFragment_MembersInjector;
import com.githubuiviewer.old.ui.userScreen.UserViewModel;
import dagger.internal.DoubleCheck;
import dagger.internal.Preconditions;
import javax.inject.Provider;
import retrofit2.Retrofit;
import retrofit2.converter.gson.GsonConverterFactory;

public final class DaggerAppComponent implements AppComponent {
  private Provider<Context> contextProvider;

  private Provider<GsonConverterFactory> provideGsonConverterFactoryProvider;

  private Provider<SharedPref> provideSharedPrefProvider;

  private Provider<Retrofit> provideRetrofitProvider;

  private Provider<GitHubService> provideGitHubReposApiProvider;

  private Provider<GitHubRepository> provideProfileRepositoryProvider;

  private DaggerAppComponent(Builder builder) {
    initialize(builder);
  }

  public static Builder builder() {
    return new Builder();
  }

  private UserViewModel getUserViewModel() {
    return new UserViewModel(
        provideProfileRepositoryProvider.get(), provideGitHubReposApiProvider.get());
  }

  private UpdateTokenViewModel getUpdateTokenViewModel() {
    return new UpdateTokenViewModel(provideProfileRepositoryProvider.get());
  }

  private IssueViewModel getIssueViewModel() {
    return new IssueViewModel(
        provideGitHubReposApiProvider.get(), provideProfileRepositoryProvider.get());
  }

  private ReadMeViewModel getReadMeViewModel() {
    return new ReadMeViewModel(provideProfileRepositoryProvider.get());
  }

  private IssuesBriefInfoViewModel getIssuesBriefInfoViewModel() {
    return new IssuesBriefInfoViewModel(provideGitHubReposApiProvider.get());
  }

  private ContributorsViewModel getContributorsViewModel() {
    return new ContributorsViewModel(provideGitHubReposApiProvider.get());
  }

  @SuppressWarnings("unchecked")
  private void initialize(final Builder builder) {
    this.contextProvider = DoubleCheck.provider(AppModule_ContextFactory.create(builder.appModule));
    this.provideGsonConverterFactoryProvider =
        DoubleCheck.provider(
            AppModule_ProvideGsonConverterFactoryFactory.create(builder.appModule));
    this.provideSharedPrefProvider =
        DoubleCheck.provider(
            AppModule_ProvideSharedPrefFactory.create(builder.appModule, contextProvider));
    this.provideRetrofitProvider =
        DoubleCheck.provider(
            AppModule_ProvideRetrofitFactory.create(
                builder.appModule,
                provideGsonConverterFactoryProvider,
                provideSharedPrefProvider,
                contextProvider));
    this.provideGitHubReposApiProvider =
        DoubleCheck.provider(
            AppModule_ProvideGitHubReposApiFactory.create(
                builder.appModule, provideRetrofitProvider));
    this.provideProfileRepositoryProvider =
        DoubleCheck.provider(
            AppModule_ProvideProfileRepositoryFactory.create(
                builder.appModule, provideGitHubReposApiProvider, provideSharedPrefProvider));
  }

  @Override
  public Context getContext() {
    return contextProvider.get();
  }

  @Override
  public void inject(UserFragment fragment) {
    injectUserFragment(fragment);
  }

  @Override
  public void inject(UpdateTokenFragment fragment) {
    injectUpdateTokenFragment(fragment);
  }

  @Override
  public void inject(BaseFragment fragment) {}

  @Override
  public void inject(IssueFragment fragment) {
    injectIssueFragment(fragment);
  }

  @Override
  public void inject(ReadMeFragment fragment) {
    injectReadMeFragment(fragment);
  }

  @Override
  public void inject(BriefInfoIssuesFragment fragment) {
    injectBriefInfoIssuesFragment(fragment);
  }

  @Override
  public void inject(ContributorsFragment fragment) {
    injectContributorsFragment(fragment);
  }

  private UserFragment injectUserFragment(UserFragment instance) {
    UserFragment_MembersInjector.injectViewModel(instance, getUserViewModel());
    return instance;
  }

  private UpdateTokenFragment injectUpdateTokenFragment(UpdateTokenFragment instance) {
    UpdateTokenFragment_MembersInjector.injectViewModel(instance, getUpdateTokenViewModel());
    return instance;
  }

  private IssueFragment injectIssueFragment(IssueFragment instance) {
    IssueFragment_MembersInjector.injectViewModel(instance, getIssueViewModel());
    return instance;
  }

  private ReadMeFragment injectReadMeFragment(ReadMeFragment instance) {
    ReadMeFragment_MembersInjector.injectViewModel(instance, getReadMeViewModel());
    return instance;
  }

  private BriefInfoIssuesFragment injectBriefInfoIssuesFragment(BriefInfoIssuesFragment instance) {
    BriefInfoIssuesFragment_MembersInjector.injectViewModel(
        instance, getIssuesBriefInfoViewModel());
    return instance;
  }

  private ContributorsFragment injectContributorsFragment(ContributorsFragment instance) {
    ContributorsFragment_MembersInjector.injectViewModel(instance, getContributorsViewModel());
    return instance;
  }

  public static final class Builder {
    private AppModule appModule;

    private Builder() {}

    public AppComponent build() {
      if (appModule == null) {
        throw new IllegalStateException(AppModule.class.getCanonicalName() + " must be set");
      }
      return new DaggerAppComponent(this);
    }

    public Builder appModule(AppModule appModule) {
      this.appModule = Preconditions.checkNotNull(appModule);
      return this;
    }
  }
}
