// Generated by Dagger (https://google.github.io/dagger).
package com.githubuiviewer.old.ui.projectScreen.issues;

import dagger.MembersInjector;
import javax.inject.Provider;

public final class BriefInfoIssuesFragment_MembersInjector
    implements MembersInjector<BriefInfoIssuesFragment> {
  private final Provider<IssuesBriefInfoViewModel> viewModelProvider;

  public BriefInfoIssuesFragment_MembersInjector(
      Provider<IssuesBriefInfoViewModel> viewModelProvider) {
    this.viewModelProvider = viewModelProvider;
  }

  public static MembersInjector<BriefInfoIssuesFragment> create(
      Provider<IssuesBriefInfoViewModel> viewModelProvider) {
    return new BriefInfoIssuesFragment_MembersInjector(viewModelProvider);
  }

  @Override
  public void injectMembers(BriefInfoIssuesFragment instance) {
    injectViewModel(instance, viewModelProvider.get());
  }

  public static void injectViewModel(
      BriefInfoIssuesFragment instance, IssuesBriefInfoViewModel viewModel) {
    instance.viewModel = viewModel;
  }
}
