// Generated by Dagger (https://google.github.io/dagger).
package com.githubuiviewer.old.ui.projectScreen.issues;

import com.githubuiviewer.newpackage.GitHubService;
import dagger.internal.Factory;
import javax.inject.Provider;

public final class IssuesBriefInfoViewModel_Factory implements Factory<IssuesBriefInfoViewModel> {
  private final Provider<GitHubService> gitHubServiceProvider;

  public IssuesBriefInfoViewModel_Factory(Provider<GitHubService> gitHubServiceProvider) {
    this.gitHubServiceProvider = gitHubServiceProvider;
  }

  @Override
  public IssuesBriefInfoViewModel get() {
    return provideInstance(gitHubServiceProvider);
  }

  public static IssuesBriefInfoViewModel provideInstance(
      Provider<GitHubService> gitHubServiceProvider) {
    return new IssuesBriefInfoViewModel(gitHubServiceProvider.get());
  }

  public static IssuesBriefInfoViewModel_Factory create(
      Provider<GitHubService> gitHubServiceProvider) {
    return new IssuesBriefInfoViewModel_Factory(gitHubServiceProvider);
  }

  public static IssuesBriefInfoViewModel newIssuesBriefInfoViewModel(GitHubService gitHubService) {
    return new IssuesBriefInfoViewModel(gitHubService);
  }
}
