// Generated by Dagger (https://google.github.io/dagger).
package com.githubuiviewer.old.ui.userScreen;

import dagger.MembersInjector;
import javax.inject.Provider;

public final class UserFragment_MembersInjector implements MembersInjector<UserFragment> {
  private final Provider<UserViewModel> viewModelProvider;

  public UserFragment_MembersInjector(Provider<UserViewModel> viewModelProvider) {
    this.viewModelProvider = viewModelProvider;
  }

  public static MembersInjector<UserFragment> create(Provider<UserViewModel> viewModelProvider) {
    return new UserFragment_MembersInjector(viewModelProvider);
  }

  @Override
  public void injectMembers(UserFragment instance) {
    injectViewModel(instance, viewModelProvider.get());
  }

  public static void injectViewModel(UserFragment instance, UserViewModel viewModel) {
    instance.viewModel = viewModel;
  }
}
