// Generated by Dagger (https://google.github.io/dagger).
package com.githubuiviewer.old.ui.userScreen;

import com.githubuiviewer.old.data.repository.GitHubRepository;
import com.githubuiviewer.newpackage.GitHubService;
import dagger.internal.Factory;
import javax.inject.Provider;

public final class UserViewModel_Factory implements Factory<UserViewModel> {
  private final Provider<GitHubRepository> gitHubRepositoryProvider;

  private final Provider<GitHubService> gitHubServiceProvider;

  public UserViewModel_Factory(
      Provider<GitHubRepository> gitHubRepositoryProvider,
      Provider<GitHubService> gitHubServiceProvider) {
    this.gitHubRepositoryProvider = gitHubRepositoryProvider;
    this.gitHubServiceProvider = gitHubServiceProvider;
  }

  @Override
  public UserViewModel get() {
    return provideInstance(gitHubRepositoryProvider, gitHubServiceProvider);
  }

  public static UserViewModel provideInstance(
      Provider<GitHubRepository> gitHubRepositoryProvider,
      Provider<GitHubService> gitHubServiceProvider) {
    return new UserViewModel(gitHubRepositoryProvider.get(), gitHubServiceProvider.get());
  }

  public static UserViewModel_Factory create(
      Provider<GitHubRepository> gitHubRepositoryProvider,
      Provider<GitHubService> gitHubServiceProvider) {
    return new UserViewModel_Factory(gitHubRepositoryProvider, gitHubServiceProvider);
  }

  public static UserViewModel newUserViewModel(
      GitHubRepository gitHubRepository, GitHubService gitHubService) {
    return new UserViewModel(gitHubRepository, gitHubService);
  }
}
