// Generated by Dagger (https://google.github.io/dagger).
package com.githubuiviewer.old.ui.projectScreen.contributors;

import com.githubuiviewer.newpackage.GitHubService;
import dagger.internal.Factory;
import javax.inject.Provider;

public final class ContributorsViewModel_Factory implements Factory<ContributorsViewModel> {
  private final Provider<GitHubService> gitHubServiceProvider;

  public ContributorsViewModel_Factory(Provider<GitHubService> gitHubServiceProvider) {
    this.gitHubServiceProvider = gitHubServiceProvider;
  }

  @Override
  public ContributorsViewModel get() {
    return provideInstance(gitHubServiceProvider);
  }

  public static ContributorsViewModel provideInstance(
      Provider<GitHubService> gitHubServiceProvider) {
    return new ContributorsViewModel(gitHubServiceProvider.get());
  }

  public static ContributorsViewModel_Factory create(
      Provider<GitHubService> gitHubServiceProvider) {
    return new ContributorsViewModel_Factory(gitHubServiceProvider);
  }

  public static ContributorsViewModel newContributorsViewModel(GitHubService gitHubService) {
    return new ContributorsViewModel(gitHubService);
  }
}
