// Generated by Dagger (https://google.github.io/dagger).
package com.githubuiviewer.old.ui.projectScreen.contributors;

import dagger.MembersInjector;
import javax.inject.Provider;

public final class ContributorsFragment_MembersInjector
    implements MembersInjector<ContributorsFragment> {
  private final Provider<ContributorsViewModel> viewModelProvider;

  public ContributorsFragment_MembersInjector(Provider<ContributorsViewModel> viewModelProvider) {
    this.viewModelProvider = viewModelProvider;
  }

  public static MembersInjector<ContributorsFragment> create(
      Provider<ContributorsViewModel> viewModelProvider) {
    return new ContributorsFragment_MembersInjector(viewModelProvider);
  }

  @Override
  public void injectMembers(ContributorsFragment instance) {
    injectViewModel(instance, viewModelProvider.get());
  }

  public static void injectViewModel(
      ContributorsFragment instance, ContributorsViewModel viewModel) {
    instance.viewModel = viewModel;
  }
}
