// Generated by Dagger (https://google.github.io/dagger).
package com.githubuiviewer.old.ui.updateTokenFragment;

import dagger.MembersInjector;
import javax.inject.Provider;

public final class UpdateTokenFragment_MembersInjector
    implements MembersInjector<UpdateTokenFragment> {
  private final Provider<UpdateTokenViewModel> viewModelProvider;

  public UpdateTokenFragment_MembersInjector(Provider<UpdateTokenViewModel> viewModelProvider) {
    this.viewModelProvider = viewModelProvider;
  }

  public static MembersInjector<UpdateTokenFragment> create(
      Provider<UpdateTokenViewModel> viewModelProvider) {
    return new UpdateTokenFragment_MembersInjector(viewModelProvider);
  }

  @Override
  public void injectMembers(UpdateTokenFragment instance) {
    injectViewModel(instance, viewModelProvider.get());
  }

  public static void injectViewModel(UpdateTokenFragment instance, UpdateTokenViewModel viewModel) {
    instance.viewModel = viewModel;
  }
}
