// Generated by Dagger (https://google.github.io/dagger).
package com.githubuiviewer.old.ui.updateTokenFragment;

import com.githubuiviewer.old.data.repository.GitHubRepository;
import dagger.internal.Factory;
import javax.inject.Provider;

public final class UpdateTokenViewModel_Factory implements Factory<UpdateTokenViewModel> {
  private final Provider<GitHubRepository> logInRepositoryProvider;

  public UpdateTokenViewModel_Factory(Provider<GitHubRepository> logInRepositoryProvider) {
    this.logInRepositoryProvider = logInRepositoryProvider;
  }

  @Override
  public UpdateTokenViewModel get() {
    return provideInstance(logInRepositoryProvider);
  }

  public static UpdateTokenViewModel provideInstance(
      Provider<GitHubRepository> logInRepositoryProvider) {
    return new UpdateTokenViewModel(logInRepositoryProvider.get());
  }

  public static UpdateTokenViewModel_Factory create(
      Provider<GitHubRepository> logInRepositoryProvider) {
    return new UpdateTokenViewModel_Factory(logInRepositoryProvider);
  }

  public static UpdateTokenViewModel newUpdateTokenViewModel(GitHubRepository logInRepository) {
    return new UpdateTokenViewModel(logInRepository);
  }
}
