// Generated by Dagger (https://google.github.io/dagger).
package com.githubuiviewer.old.ui.projectScreen.readme;

import com.githubuiviewer.old.data.repository.GitHubRepository;
import dagger.internal.Factory;
import javax.inject.Provider;

public final class ReadMeViewModel_Factory implements Factory<ReadMeViewModel> {
  private final Provider<GitHubRepository> gitHubRepositoryProvider;

  public ReadMeViewModel_Factory(Provider<GitHubRepository> gitHubRepositoryProvider) {
    this.gitHubRepositoryProvider = gitHubRepositoryProvider;
  }

  @Override
  public ReadMeViewModel get() {
    return provideInstance(gitHubRepositoryProvider);
  }

  public static ReadMeViewModel provideInstance(
      Provider<GitHubRepository> gitHubRepositoryProvider) {
    return new ReadMeViewModel(gitHubRepositoryProvider.get());
  }

  public static ReadMeViewModel_Factory create(
      Provider<GitHubRepository> gitHubRepositoryProvider) {
    return new ReadMeViewModel_Factory(gitHubRepositoryProvider);
  }

  public static ReadMeViewModel newReadMeViewModel(GitHubRepository gitHubRepository) {
    return new ReadMeViewModel(gitHubRepository);
  }
}
