// Generated by Dagger (https://google.github.io/dagger).
package com.githubuiviewer.old.ui.projectScreen.readme;

import dagger.MembersInjector;
import javax.inject.Provider;

public final class ReadMeFragment_MembersInjector implements MembersInjector<ReadMeFragment> {
  private final Provider<ReadMeViewModel> viewModelProvider;

  public ReadMeFragment_MembersInjector(Provider<ReadMeViewModel> viewModelProvider) {
    this.viewModelProvider = viewModelProvider;
  }

  public static MembersInjector<ReadMeFragment> create(
      Provider<ReadMeViewModel> viewModelProvider) {
    return new ReadMeFragment_MembersInjector(viewModelProvider);
  }

  @Override
  public void injectMembers(ReadMeFragment instance) {
    injectViewModel(instance, viewModelProvider.get());
  }

  public static void injectViewModel(ReadMeFragment instance, ReadMeViewModel viewModel) {
    instance.viewModel = viewModel;
  }
}
